spring:
  application:
    name: ums
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql2.sqlpub.com:3307/ahuzsp
    username: ahuzsp
    password: x1vGhJVfT3JWgZ98

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
